pony_list:
    pattern:      /pony.{_format}
    defaults:     { _controller: CleverAgeSymfponyBundle:Default:index, _format: xml }
    requirements: { _format: (xml|json), _method: GET }

pony_show:
    pattern:      /pony/{slug}.{_format}
    defaults:     { _controller: CleverAgeSymfponyBundle:Default:show, _format: xml }
    requirements: { _format: (xml|json), _method: GET, slug: "[a-z0-9-]+" }

pony_delete:
    pattern:      /pony/{slug}.{_format}
    defaults:     { _controller: CleverAgeSymfponyBundle:Default:delete, _format: xml }
    requirements: { _format: (xml|json), _method: DELETE, slug: "[a-z0-9-]+" }