pony_list:
    pattern:      /pony.{_format}
    defaults:     { _controller: CleverAgeSymfponyBundle:Default:index, _format: xml }
    requirements: { _format: (xml|json), _method: GET }

pony_show:
    pattern:      /pony/{slug}.{_format}
    defaults:     { _controller: CleverAgeSymfponyBundle:Default:show, _format: xml }
    requirements: { _format: (xml|json), _method: GET, slug: "[a-z0-9-]+" }


#
#pony_list:
#  url: /pony.:sf_format
#  param: { module: pony, action: index, sf_format: xml }
#  class: sfRequestRoute
#  requirements: { sf_method: GET, sf_format: (xml|json|yml) }
#
#pony_show:
#  url: /pony/:slug.:sf_format
#  param: { module: pony, action: show, sf_format: xml }
#  class: sfDoctrineRoute
#  options: { model: Pony, column: slug, type: object }
#  requirements: { sf_method: GET, sf_format: (xml|json|yml) }
#
#pony_delete:
#  url: /pony/:slug.:sf_format
#  param: { module: pony, action: delete, sf_format: xml }
#  class: sfDoctrineRoute
#  options: { model: Pony, column: slug, type: object }
#  requirements: { sf_method: DELETE, sf_format: (xml|json|yml) }