<?php

/**
 * PonyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PonyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PonyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pony');
    }
}