<?php

/**
 * Pony
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfpony
 * @subpackage model
 * @author     Paellas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pony extends BasePony
{
}
