imports:
    - { resource: dist.yml }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['php'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
#twig:
#    debug:            %kernel.debug%
#    strict_variables: %kernel.debug%

doctrine:
    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
            CleverAgeSymfponyBundle:  { type: annotation }

# doctrine extensions configuration
stof_doctrine_extensions:
    orm:
        default:
            # only enable sluggable listener
            tree: false
            timestampable: false
            translatable: false
