#!/usr/bin/env php
<?php

require_once __DIR__.'/Symfpony2Kernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new Symfpony2Kernel('dev', true);

$application = new Application($kernel);
$application->run();
