Pony:
  columns:
    name:
      type: string(255)
    picture_url:
      type: string(255)
    description:
      type: text
  actAs:
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: false