# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

pony_list:
  url: /pony.:sf_format
  param: { module: pony, action: index, sf_format: xml }
  class: sfRequestRoute
  requirements: { sf_method: GET }

pony_show:
  url: /pony/:slug.:sf_format
  param: { module: pony, action: show, sf_format: xml }
  class: sfDoctrineRoute
  options: { model: Pony, column: slug, type: object }
  requirements: { sf_method: GET }

pony_delete:
  url: /pony/:slug.:sf_format
  param: { module: pony, action: delete, sf_format: xml }
  class: sfDoctrineRoute
  options: { model: Pony, column: slug, type: object }
  requirements: { sf_method: DELETE }